### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by hide212131** [jhipster/generator-jhipster-native#104]
The following issue has been resolved, so I believe it is appropriate to proceed with a major version update:
https://github.com/jhipster/generator-jhipster-native/pull/102

Additionally, I suggest merging the issue below (Please let me know if you have anything to add):
https://github.com/jhipster/generator-jhipster-native/pull/91

**Comment by mraible** [comment]
@hide212131 Can this be closed since v2.0.0 has been released?

FYI... Spring Boot 3.2.1 and 3.2.2 do not work with GraalVM when using Spring MVC and Spring Security. It works fine with WebFlux and both of these versions. See https://github.com/spring-projects/spring-security/issues/14362 for more information.

**Comment by hide212131** [comment]
Thank you, @mraible. Yes, I will close this issue. 
The information about 3.2.2 is very helpful. It seems we'll be on hold here until the release of generator-jhipster compatible with version 3.3.3.
